name: pypi-release

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # setup python
    - uses: actions/checkout@v7
    - name: set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.11"
    - name: install pypa/build
      run: >-
        python -m
        pip install build --user
    
    # package & store artifacts
    - name: package the pypi
      run: |
        python -m build
    - name: store the distribution packages
      uses: actions/upload-artifact@v7
      with:
        name: python-package-distributions
        path: dist/
  
  publish-to-pypi:
    # only publish to PyPI on tag pushes
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/r/rpi2home-assistant
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v8
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
